import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Providers from "@/components/Providers";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Footer from "@/components/Footer";
import { OrderProvider } from '@/context/OrderContext';
import { ToastContainer, toast } from 'react-toastify';
import { AuthProvider } from '@/context/AuthContext'; 
const tajawal = localFont({
  src: [
    {
      path: "./../../../public/font/Tajawal-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../../public/font/Tajawal-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../../public/font/Tajawal-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-tajawal",
});

export const metadata = {
  title: "SetAlkel",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();


  return (
    <html>
      <body className={`${tajawal.className} relative`}>
        <AuthProvider> 
        <OrderProvider>
          <NextIntlClientProvider messages={messages}>
            <Providers>
              <Header />
              <ToastContainer />
              {children}
              <Footer />
            </Providers>
          </NextIntlClientProvider>
        </OrderProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
